variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v2_9_1_FULL.zip'
  
jobs:
  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSAgoraVideoWithSenseTime'
      workingDirectory: 'Agora-Video-With-SenseTime-iOS'
      scheme: 'Agora-With-SenseTime'
      sdkurl: $(iOSRTCSDK)
