# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautifyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeautifyExample
  pod 'AGMCapturer_iOS', '~> 2.0.0'
  pod 'AgoraRtcEngine_iOS', '~> 3.3.1'

end
